spring:
  application:
    name: Jusangbokhap
  profiles:
    active: prod

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    org.springframework: DEBUG

kakao:
  api:
    admin-key: ""
    cid: "TC0ONETIME"
    approval-url: "https://frontend.com/payments/approve"
    cancel-url: "https://frontend.com/payments/cancel"
    fail-url: "https://frontend.com/payments/fail"
    key: ${KAKAO_API_KEY}

elasticsearch:
  custom:
    host: ${ELASTICSEARCH_HOST}
    port: ${ELASTICSEARCH_PORT}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
    certificate: ${ELASTICSEARCH_CERTIFICATE}
    search:
      index-name:
        search-keyword
      top-index-name:
        top-keywords

redis:
  search:
    rank:
      search:rank
    meta:
      search:meta
    meta-last-updated:
      last-updated

search:
  key:
    realtime-keywords
  result_key:
    realtime-keywords-result

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics,info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/jusangbokhap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: jusangbokhap
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/jusangbokhap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      database: jusangbokhap_test
      host: localhost
      port: 27017
    redis:
      port: 6379
      host: localhost
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@cluster0.5ly7k.mongodb.net/${MONGO_DB}?retryWrites=true&w=majority&appName=Cluster0
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  cache:
    type: redis
    redis:
      time-to-live: 1800000
      enable-statistics: true
  session:
    redis:
      namespace: spring:session
      flush-mode: on_save
    timeout: 1800
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

management:
  endpoint:
    health:
      show-details: when_authorized