spring:
  application:
    name: Jusangbokhap
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/jusangbokhap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  datasource:
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
#  datasource:
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379

management:
  health:
    elasticsearch:
      enabled: false

server:
  port: 8080


elasticsearch:
  custom:
    host: ${ELASTICSEARCH_HOST}
    port: ${ELASTICSEARCH_PORT}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
    certificate: ${ELASTICSEARCH_CERTIFICATE}
    search:
      index-name:
        search-keyword
      top-index-name:
        top-keywords

redis:
  search:
    rank:
      search:rank
    meta:
      search:meta
    meta-last-updated:
      last-updated



search:
  key:
    realtime-keywords
  result_key:
    realtime-keywords-result