spring:
  application:
    name: Jusangbokhap

  redis:
    host: localhost
    port: 6379
    timeout: 60000

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    org.springframework: DEBUG

kakao:
  api:
    admin-key: ""
    cid: "TC0ONETIME"
    approval-url: "https://frontend.com/payments/approve"
    cancel-url: "https://frontend.com/payments/cancel"
    fail-url: "https://frontend.com/payments/fail"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/jusangbokhap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/jusangbokhap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080
