spring:
  application:
    name: Jusangbokhap
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/jusangbokhap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/chatdb?authSource=admin
      username: root
      password: root
      auto-index-creation: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/jusangbokhap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/chatdb?authSource=admin
      username: root
      password: root
      auto-index-creation: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST}:27017/${MONGODB_NAME}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}

server:
  port: 8080