spring:
  application:
    name: Jusangbokhap

  redis:
    host: localhost
    port: 6379
    timeout: 60000

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    org.springframework: DEBUG

kakao:
  api:
    admin-key: ""
    cid: "TC0ONETIME"
    approval-url: "https://frontend.com/payments/approve"
    cancel-url: "https://frontend.com/payments/cancel"
    fail-url: "https://frontend.com/payments/fail"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics,info
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/jusangbokhap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/chatdb?authSource=admin
      username: root
      password: root
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/jusangbokhap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      database: jusangbokhap_test
      host: localhost
      port: 27017
    redis:
      port: 6379
      host: localhost
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@cluster0.5ly7k.mongodb.net/${MONGO_DB}?retryWrites=true&w=majority&appName=Cluster0
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  cache:
    type: redis
    redis:
      time-to-live: 1800000
      enable-statistics: true
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
    timeout: 1800
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      enabled: true

server:
  port: 8080
