apiVersion: v1
kind: ConfigMap
metadata:
  name: jusangbokhap-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  TZ: "Asia/Seoul"
  SERVER_PORT: "8080"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

  SPRING_DATA_MONGODB_URI: "mongodb+srv://jinho7329:${MONGO_PASSWORD}@cluster0.5ly7k.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  SPRING_DATA_MONGODB_DATABASE: "jusangbokhap"
  SPRING_DATA_MONGODB_SSL_ENABLED: "true"

  SPRING_DATA_MONGODB_CONNECTION_TIMEOUT: "5000"
  SPRING_DATA_MONGODB_SOCKET_TIMEOUT: "6000"
  SPRING_DATA_MONGODB_MAX_WAIT_TIME: "5000"

  SPRING_DATA_REDIS_TIMEOUT: "60000"
  SPRING_DATA_REDIS_SSL: "false"
  SPRING_DATA_REDIS_DATABASE: "0"

  SPRING_CACHE_TYPE: "redis"
  SPRING_CACHE_REDIS_TIME_TO_LIVE: "3600000"
  SPRING_CACHE_REDIS_ENABLE_STATISTICS: "true"

  SPRING_SESSION_STORE_TYPE: "redis"
  SPRING_SESSION_REDIS_FLUSH_MODE: "on_save"
  SPRING_SESSION_REDIS_NAMESPACE: "spring:session"