apiVersion: apps/v1
kind: Deployment
metadata:
  name: jusangbokhap-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jusangbokhap-app
  template:
    metadata:
      labels:
        app: jusangbokhap-app
    spec:
      containers:
        - name: jusangbokhap-app
          image: 850995539111.dkr.ecr.ap-northeast-2.amazonaws.com/jusangbokhap
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: jusangbokhap-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 30
