apiVersion: apps/v1
kind: Deployment
metadata:
  name: jusangbokhap-app
  labels:
    app: jusangbokhap-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jusangbokhap-app
  template:
    metadata:
      labels:
        app: jusangbokhap-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: jusangbokhap-app
          image: 850995539111.dkr.ecr.ap-northeast-2.amazonaws.com/jusangbokhap
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: jusangbokhap-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,prometheus,metrics"
            - name: ELASTICSEARCH_HOST
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-config
                  key: host
            - name: ELASTICSEARCH_PORT
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-config
                  key: port
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-config
                  key: username
            - name: ELASTICSEARCH_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-cert
                  key: certificate
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 180
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/health
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 30
