apiVersion: v1
kind: Service
metadata:
  name: jusangbokhap-app-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
  labels:
    app: jusangbokhap-app

spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
  selector:
    app: jusangbokhap-app