name: CD

on:
  push:
    branches:
      - main
      - dev
      - KR-109-chore/setup-ci

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker Image
        run: |
          docker build -t jusangbokhap:${{ github.sha }} . docker tag jusangbokhap:${{ github.sha }} jusangbokhap:latest

      - name: Deploy to Dev Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/ec2-user/juangbokhap
            docker-compose down
            docker-compose up -d
            docker image prune -f