name: JAVA CI with Gradle

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "feat/**", "feature/**", "fix/**", "KR-123-chore/kr-123"]
    paths-ignore:
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build, test and analyze
        run: ./gradlew build test jacocoTestReport --info

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/reports/tests/test/
            build/test-results/test/
            build/reports/jacoco/test/